server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  data:
    mongodb:
      uri: mongodb://auth-food-mongo-srv:27017/auth?directConnection=true
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: http://auth-food-order-srv:8080
          predicates:
            - Path=/api/v1/auth/**
    config:
      import-check:
        enabled: false

