server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  data:
    mongodb:
      uri: ${AUTH_MONGO_URL:mongodb://localhost:27017/auth}
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: ${AUTH_URL:http://localhost:8080}
          predicates:
            - Path=/api/v1/auth/**
        - id: MENU-SERVICE
          uri: ${MENU_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/menu/**
    config:
      import-check:
        enabled: false

secure_key: SECURE_KEY

